/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'USER12' at '7/7/16 10:08 PM' with Gradle 2.13
 *
 * @author USER12, @date 7/7/16 10:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
